// <auto-generated />
namespace AdBoard.WebUI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddFav : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddFav));
        
        string IMigrationMetadata.Id
        {
            get { return "201504152301194_AddFav"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
